{"pageProps":{"post":{"title":"Jest parallelization, globals, mocks, and squawkless tests","date":"2021-10-05","slug":"2021-10-05-jest","html":"<p>I found that there is a little bit of confusion and misunderstanding around how\nthings like parallelization work in jest, which sometimes leads to additional\nhacking around problems that may not exist or speculating incorrectly about\ntest failure. This is also of course a point of concern when you have code that\nfor some reason or another uses global variables. Here are a short summary of\nthings that may cause confusion.</p>\n<h2>Tests in a single file are NOT run in parallel</h2>\n<p>Simple example, the global variable r is included in the test condition, but it\nis accurately run in all cases because the tests are not run in parallel.</p>\n<pre><code class=\"language-js\">let r = 0\n\nfunction timeout(ms) {\n  return new Promise(resolve => setTimeout(resolve, ms))\n}\n\ndescribe('tests', () => {\n  it('t1', async () => {\n    await timeout(1000)\n    expect(r).toBe(0)\n    r++\n  })\n  it('t2', async () => {\n    await timeout(1000)\n    expect(r).toBe(1)\n    r++\n  })\n  it('t3', async () => {\n    await timeout(1000)\n    expect(r).toBe(2)\n    r++\n  })\n})\n</code></pre>\n<p>This test will take 3 seconds, and will accurately count the global variable.\nIf it was in parallel, it may only take 1 second, and would inaccurately count\nthe global variable due to race conditions</p>\n<h2>Tests in different files ARE run in parallel</h2>\n<p>Let's take another example where we use a global variable, and then two\ndifferent tests use the global variable.</p>\n<p>file_using_some_globals.js</p>\n<pre><code class=\"language-js\">let myGlobal = 0\n\nexport function doStuff() {\n  myGlobal++\n  return myGlobal\n}\n\nexport function resetMyGlobal() {\n  myGlobal = 0\n}\n\nexport function timeout(ms) {\n  return new Promise(resolve => setTimeout(resolve, ms))\n}\n</code></pre>\n<p>test_global_vars1.test.js</p>\n<pre><code class=\"language-js\">import { doStuff, timeout } from './dostuff'\ntest('file1', async () => {\n  doStuff()\n  await timeout(1000)\n  expect(doStuff()).toEqual(2)\n})\n</code></pre>\n<p>test_global_vars2.test.js</p>\n<pre><code class=\"language-js\">import { doStuff, timeout } from './dostuff'\n\ntest('file1', async () => {\n  await timeout(1000)\n  expect(doStuff()).toEqual(1)\n})\n</code></pre>\n<p>This test completes in less than 2 seconds, and these tests are run in\nparallel. They use different instances of the global state, and therefore have\nno worries with colliding their state.</p>\n<h2>Does a mock from one test affect another test?</h2>\n<p>While seeking the fabled \"squawk-less\" test, it is often useful to mock console\nso that tests that produce an expected error don't actually print an error\nmessage. However, if not done carefully, you will remove errors across tests</p>\n<p>So, could a mock from one test affect another test? If it's in the same file,\nyes!</p>\n<p>mock_console.test.js</p>\n<pre><code class=\"language-js\">test('test1', () => {\n  console.error = jest.fn()\n  console.error('wow')\n  expect(console.error).toHaveBeenCalled()\n})\n\ntest('test2', () => {\n  // this console.error will not appear because test1 mocked away console.error\n  // without restoring it\n  console.error(\"Help I can't see!\")\n})\n</code></pre>\n<p>To properly mock these, you should restore the console mock at the end of your\nfunction</p>\n<pre><code class=\"language-js\">test('test1', () => {\n  const orig = console.error\n  console.error = jest.fn()\n  console.error('I should not see this!')\n  expect(console.error).toHaveBeenCalled()\n  console.error = orig\n})\n\ntest('test2', () => {\n  const consoleMock = jest.spyOn(console, 'error').mockImplementation()\n  console.error('I should not see this!')\n  consoleMock.mockRestore()\n})\n\ntest('test3', () => {\n  console.error('I should see this error!')\n})\n</code></pre>\n<h2>Add-on: Achieve squawkless tests!</h2>\n<p>Your test output should just be a big list of PASS statements, not interleaved\nwith console.error outputs from when you are testing error conditions of your\ncode</p>\n<p>\"Squawkless tests\" is a term I made up, but it means that if you have code\nunder test that prints some errors to the console, then mock the console.error\nfunction, as in the previous section. Don't stand for having a bunch of verbose\nerrors in your CI logs! However, I also suggest only mocking out console.error\nfor tests that are <strong>expected</strong> to have errors, lest you paper over unexpected\nerrors.</p>\n<p><img src=\"/media/squawkless_tests.png\" alt=\"\"></p>\n<p>Figure: a nice clean test suite without a bunch of crazy console.error outputs</p>\n<h2>Conclusion</h2>\n<p>Getting better at testing requires exercise, and understanding the basics of\nyour tools can help! Hopefully this helps you achieve a better understanding\nand write cleaner jest tests.</p>"}},"__N_SSG":true}