<!DOCTYPE html><html lang="en"><head><link rel="shortcut icon" href="favicon.ico"/><link rel="alternate" type="application/rss+xml" href="/rss.xml"/><meta name="description" content="Blogging for the future"/><script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.25.0/prism.min.js" integrity="sha512-hpZ5pDCF2bRCweL5WoA0/N1elet1KYL5mx3LP555Eg/0ZguaHawxNvEjF6O3rufAChs16HVNhEc6blF/rZoowQ==" crossorigin="anonymous" referrerPolicy="no-referrer"></script><meta name="viewport" content="width=device-width"/><meta charSet="utf-8"/><title>Jest parallelization, globals, mocks, and squawkless tests</title><meta name="next-head-count" content="3"/><link rel="preload" href="/_next/static/css/53d80a6545e3cb78.css" as="style"/><link rel="stylesheet" href="/_next/static/css/53d80a6545e3cb78.css" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-5cd94c89d3acac5f.js"></script><script src="/_next/static/chunks/webpack-514908bffb652963.js" defer=""></script><script src="/_next/static/chunks/framework-91d7f78b5b4003c8.js" defer=""></script><script src="/_next/static/chunks/main-d98b4a7f39fdfc80.js" defer=""></script><script src="/_next/static/chunks/pages/_app-76cd57bf65f05d70.js" defer=""></script><script src="/_next/static/chunks/pages/posts/%5Bslug%5D-e25dfd02a0d6b075.js" defer=""></script><script src="/_next/static/QlcBmpCz4ymap0WgniBDb/_buildManifest.js" defer=""></script><script src="/_next/static/QlcBmpCz4ymap0WgniBDb/_ssgManifest.js" defer=""></script><script src="/_next/static/QlcBmpCz4ymap0WgniBDb/_middlewareManifest.js" defer=""></script></head><body><div id="__next" data-reactroot=""><div><main><div><div style="margin-bottom:100px"><a href="/">Misc scribbles</a></div><article><div><h1>Jest parallelization, globals, mocks, and squawkless tests</h1><h4>2021-10-05</h4></div><p>I found that there is a little bit of confusion and misunderstanding around how
things like parallelization work in jest, which sometimes leads to additional
hacking around problems that may not exist or speculating incorrectly about
test failure. This is also of course a point of concern when you have code that
for some reason or another uses global variables. Here are a short summary of
things that may cause confusion.</p><h2>Tests in a single file are NOT run in parallel</h2><p>Simple example, the global variable r is included in the test condition, but it
is accurately run in all cases because the tests are not run in parallel.</p><pre><code class="language-js">let r = 0

function timeout(ms) {
  return new Promise(resolve =&gt; setTimeout(resolve, ms))
}

describe(&#x27;tests&#x27;, () =&gt; {
  it(&#x27;t1&#x27;, async () =&gt; {
    await timeout(1000)
    expect(r).toBe(0)
    r++
  })
  it(&#x27;t2&#x27;, async () =&gt; {
    await timeout(1000)
    expect(r).toBe(1)
    r++
  })
  it(&#x27;t3&#x27;, async () =&gt; {
    await timeout(1000)
    expect(r).toBe(2)
    r++
  })
})
</code></pre><p>This test will take 3 seconds, and will accurately count the global variable.
If it was in parallel, it may only take 1 second, and would inaccurately count
the global variable due to race conditions</p><h2>Tests in different files ARE run in parallel</h2><p>Let&#x27;s take another example where we use a global variable, and then two
different tests use the global variable.</p><p>file_using_some_globals.js</p><pre><code class="language-js">let myGlobal = 0

export function doStuff() {
  myGlobal++
  return myGlobal
}

export function resetMyGlobal() {
  myGlobal = 0
}

export function timeout(ms) {
  return new Promise(resolve =&gt; setTimeout(resolve, ms))
}
</code></pre><p>test_global_vars1.test.js</p><pre><code class="language-js">import { doStuff, timeout } from &#x27;./dostuff&#x27;
test(&#x27;file1&#x27;, async () =&gt; {
  doStuff()
  await timeout(1000)
  expect(doStuff()).toEqual(2)
})
</code></pre><p>test_global_vars2.test.js</p><pre><code class="language-js">import { doStuff, timeout } from &#x27;./dostuff&#x27;

test(&#x27;file1&#x27;, async () =&gt; {
  await timeout(1000)
  expect(doStuff()).toEqual(1)
})
</code></pre><p>This test completes in less than 2 seconds, and these tests are run in
parallel. They use different instances of the global state, and therefore have
no worries with colliding their state.</p><h2>Does a mock from one test affect another test?</h2><p>While seeking the fabled &quot;squawk-less&quot; test, it is often useful to mock console
so that tests that produce an expected error don&#x27;t actually print an error
message. However, if not done carefully, you will remove errors across tests</p><p>So, could a mock from one test affect another test? If it&#x27;s in the same file,
yes!</p><p>mock_console.test.js</p><pre><code class="language-js">test(&#x27;test1&#x27;, () =&gt; {
  console.error = jest.fn()
  console.error(&#x27;wow&#x27;)
  expect(console.error).toHaveBeenCalled()
})

test(&#x27;test2&#x27;, () =&gt; {
  // this console.error will not appear because test1 mocked away console.error
  // without restoring it
  console.error(&quot;Help I can&#x27;t see!&quot;)
})
</code></pre><p>To properly mock these, you should restore the console mock at the end of your
function</p><pre><code class="language-js">test(&#x27;test1&#x27;, () =&gt; {
  const orig = console.error
  console.error = jest.fn()
  console.error(&#x27;I should not see this!&#x27;)
  expect(console.error).toHaveBeenCalled()
  console.error = orig
})

test(&#x27;test2&#x27;, () =&gt; {
  const consoleMock = jest.spyOn(console, &#x27;error&#x27;).mockImplementation()
  console.error(&#x27;I should not see this!&#x27;)
  consoleMock.mockRestore()
})

test(&#x27;test3&#x27;, () =&gt; {
  console.error(&#x27;I should see this error!&#x27;)
})
</code></pre><h2>Add-on: Achieve squawkless tests!</h2><p>Your test output should just be a big list of PASS statements, not interleaved
with console.error outputs from when you are testing error conditions of your
code</p><p>&quot;Squawkless tests&quot; is a term I made up, but it means that if you have code
under test that prints some errors to the console, then mock the console.error
function, as in the previous section. Don&#x27;t stand for having a bunch of verbose
errors in your CI logs! However, I also suggest only mocking out console.error
for tests that are <strong>expected</strong> to have errors, lest you paper over unexpected
errors.</p><p><img src="/media/squawkless_tests.png"/></p><p>Figure: a nice clean test suite without a bunch of crazy console.error outputs</p><h2>Conclusion</h2><p>Getting better at testing requires exercise, and understanding the basics of
your tools can help! Hopefully this helps you achieve a better understanding
and write cleaner jest tests.</p></article></div></main></div><footer style="margin-top:100px"><a href="/">Home</a> <a href="/archive">Blog archive</a> <a href="https://github.com/cmdcolin">Github</a> <a href="https://twitter.com/cmdcolin">Twitter</a> <a href="/projects">Projects</a> <a href="/photos">Photos</a> <a href="/kitty">Kitty</a> <a href="/rss.xml">RSS</a><a href="/about">About</a> </footer></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"post":{"title":"Jest parallelization, globals, mocks, and squawkless tests","date":"2021-10-05","slug":"2021-10-05-jest","mdxSource":{"compiledSource":"var p=Object.defineProperty,h=Object.defineProperties;var m=Object.getOwnPropertyDescriptors;var a=Object.getOwnPropertySymbols;var n=Object.prototype.hasOwnProperty,l=Object.prototype.propertyIsEnumerable;var i=(e,t,o)=\u003et in e?p(e,t,{enumerable:!0,configurable:!0,writable:!0,value:o}):e[t]=o,r=(e,t)=\u003e{for(var o in t||(t={}))n.call(t,o)\u0026\u0026i(e,o,t[o]);if(a)for(var o of a(t))l.call(t,o)\u0026\u0026i(e,o,t[o]);return e},c=(e,t)=\u003eh(e,m(t));var u=(e,t)=\u003e{var o={};for(var s in e)n.call(e,s)\u0026\u0026t.indexOf(s)\u003c0\u0026\u0026(o[s]=e[s]);if(e!=null\u0026\u0026a)for(var s of a(e))t.indexOf(s)\u003c0\u0026\u0026l.call(e,s)\u0026\u0026(o[s]=e[s]);return o};const layoutProps={},MDXLayout=\"wrapper\";function MDXContent(o){var s=o,{components:e}=s,t=u(s,[\"components\"]);return mdx(MDXLayout,c(r(r({},layoutProps),t),{components:e,mdxType:\"MDXLayout\"}),mdx(\"p\",null,`I found that there is a little bit of confusion and misunderstanding around how\nthings like parallelization work in jest, which sometimes leads to additional\nhacking around problems that may not exist or speculating incorrectly about\ntest failure. This is also of course a point of concern when you have code that\nfor some reason or another uses global variables. Here are a short summary of\nthings that may cause confusion.`),mdx(\"h2\",null,\"Tests in a single file are NOT run in parallel\"),mdx(\"p\",null,`Simple example, the global variable r is included in the test condition, but it\nis accurately run in all cases because the tests are not run in parallel.`),mdx(\"pre\",null,mdx(\"code\",r({parentName:\"pre\"},{className:\"language-js\"}),`let r = 0\n\nfunction timeout(ms) {\n  return new Promise(resolve =\u003e setTimeout(resolve, ms))\n}\n\ndescribe('tests', () =\u003e {\n  it('t1', async () =\u003e {\n    await timeout(1000)\n    expect(r).toBe(0)\n    r++\n  })\n  it('t2', async () =\u003e {\n    await timeout(1000)\n    expect(r).toBe(1)\n    r++\n  })\n  it('t3', async () =\u003e {\n    await timeout(1000)\n    expect(r).toBe(2)\n    r++\n  })\n})\n`)),mdx(\"p\",null,`This test will take 3 seconds, and will accurately count the global variable.\nIf it was in parallel, it may only take 1 second, and would inaccurately count\nthe global variable due to race conditions`),mdx(\"h2\",null,\"Tests in different files ARE run in parallel\"),mdx(\"p\",null,`Let's take another example where we use a global variable, and then two\ndifferent tests use the global variable.`),mdx(\"p\",null,\"file_using_some_globals.js\"),mdx(\"pre\",null,mdx(\"code\",r({parentName:\"pre\"},{className:\"language-js\"}),`let myGlobal = 0\n\nexport function doStuff() {\n  myGlobal++\n  return myGlobal\n}\n\nexport function resetMyGlobal() {\n  myGlobal = 0\n}\n\nexport function timeout(ms) {\n  return new Promise(resolve =\u003e setTimeout(resolve, ms))\n}\n`)),mdx(\"p\",null,\"test_global_vars1.test.js\"),mdx(\"pre\",null,mdx(\"code\",r({parentName:\"pre\"},{className:\"language-js\"}),`import { doStuff, timeout } from './dostuff'\ntest('file1', async () =\u003e {\n  doStuff()\n  await timeout(1000)\n  expect(doStuff()).toEqual(2)\n})\n`)),mdx(\"p\",null,\"test_global_vars2.test.js\"),mdx(\"pre\",null,mdx(\"code\",r({parentName:\"pre\"},{className:\"language-js\"}),`import { doStuff, timeout } from './dostuff'\n\ntest('file1', async () =\u003e {\n  await timeout(1000)\n  expect(doStuff()).toEqual(1)\n})\n`)),mdx(\"p\",null,`This test completes in less than 2 seconds, and these tests are run in\nparallel. They use different instances of the global state, and therefore have\nno worries with colliding their state.`),mdx(\"h2\",null,\"Does a mock from one test affect another test?\"),mdx(\"p\",null,`While seeking the fabled \"squawk-less\" test, it is often useful to mock console\nso that tests that produce an expected error don't actually print an error\nmessage. However, if not done carefully, you will remove errors across tests`),mdx(\"p\",null,`So, could a mock from one test affect another test? If it's in the same file,\nyes!`),mdx(\"p\",null,\"mock_console.test.js\"),mdx(\"pre\",null,mdx(\"code\",r({parentName:\"pre\"},{className:\"language-js\"}),`test('test1', () =\u003e {\n  console.error = jest.fn()\n  console.error('wow')\n  expect(console.error).toHaveBeenCalled()\n})\n\ntest('test2', () =\u003e {\n  // this console.error will not appear because test1 mocked away console.error\n  // without restoring it\n  console.error(\"Help I can't see!\")\n})\n`)),mdx(\"p\",null,`To properly mock these, you should restore the console mock at the end of your\nfunction`),mdx(\"pre\",null,mdx(\"code\",r({parentName:\"pre\"},{className:\"language-js\"}),`test('test1', () =\u003e {\n  const orig = console.error\n  console.error = jest.fn()\n  console.error('I should not see this!')\n  expect(console.error).toHaveBeenCalled()\n  console.error = orig\n})\n\ntest('test2', () =\u003e {\n  const consoleMock = jest.spyOn(console, 'error').mockImplementation()\n  console.error('I should not see this!')\n  consoleMock.mockRestore()\n})\n\ntest('test3', () =\u003e {\n  console.error('I should see this error!')\n})\n`)),mdx(\"h2\",null,\"Add-on: Achieve squawkless tests!\"),mdx(\"p\",null,`Your test output should just be a big list of PASS statements, not interleaved\nwith console.error outputs from when you are testing error conditions of your\ncode`),mdx(\"p\",null,`\"Squawkless tests\" is a term I made up, but it means that if you have code\nunder test that prints some errors to the console, then mock the console.error\nfunction, as in the previous section. Don't stand for having a bunch of verbose\nerrors in your CI logs! However, I also suggest only mocking out console.error\nfor tests that are `,mdx(\"strong\",{parentName:\"p\"},\"expected\"),` to have errors, lest you paper over unexpected\nerrors.`),mdx(\"p\",null,mdx(\"img\",r({parentName:\"p\"},{src:\"/media/squawkless_tests.png\",alt:null}))),mdx(\"p\",null,\"Figure: a nice clean test suite without a bunch of crazy console.error outputs\"),mdx(\"h2\",null,\"Conclusion\"),mdx(\"p\",null,`Getting better at testing requires exercise, and understanding the basics of\nyour tools can help! Hopefully this helps you achieve a better understanding\nand write cleaner jest tests.`))}MDXContent.isMDXComponent=!0;\n","scope":{}}}},"__N_SSG":true},"page":"/posts/[slug]","query":{"slug":"2021-10-05-jest"},"buildId":"QlcBmpCz4ymap0WgniBDb","isFallback":false,"gsp":true,"scriptLoader":[]}</script></body></html>