<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><title>Memoizing async functions so that you don&#x27;t cache errors</title><meta name="next-head-count" content="3"/><link rel="shortcut icon" href="favicon.ico"/><link rel="alternate" type="application/rss+xml" href="/rss.xml"/><meta name="description" content="Blogging for the future"/><script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.25.0/prism.min.js" integrity="sha512-hpZ5pDCF2bRCweL5WoA0/N1elet1KYL5mx3LP555Eg/0ZguaHawxNvEjF6O3rufAChs16HVNhEc6blF/rZoowQ==" crossorigin="anonymous" referrerPolicy="no-referrer"></script><link rel="preload" href="/_next/static/css/9d066bf523979bbf.css" as="style"/><link rel="stylesheet" href="/_next/static/css/9d066bf523979bbf.css" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script><script src="/_next/static/chunks/webpack-8b306f51a35d80a9.js" defer=""></script><script src="/_next/static/chunks/framework-c0d8f0fd2eea5ac1.js" defer=""></script><script src="/_next/static/chunks/main-b12cd062888056b2.js" defer=""></script><script src="/_next/static/chunks/pages/_app-d9139de5c3de3b6b.js" defer=""></script><script src="/_next/static/chunks/996-3d2a4318c0ac6f1a.js" defer=""></script><script src="/_next/static/chunks/pages/posts/%5Bslug%5D-586b38a9b3457703.js" defer=""></script><script src="/_next/static/N960rXq5BRJ06uZqtuld9/_buildManifest.js" defer=""></script><script src="/_next/static/N960rXq5BRJ06uZqtuld9/_ssgManifest.js" defer=""></script></head><body><div id="__next"><div><main><div><div style="margin-bottom:100px"><a href="/">Misc scribbles</a></div><article><div><h1>Memoizing async functions so that you don&#x27;t cache errors</h1><h4>2022-02-26</h4></div><div><p>There are two hard problems in computer science: <a href="https://martinfowler.com/bliki/TwoHardThings.html">Cache invalidation and naming
things</a>. In this post we'll
show how memoize an async function, and how to invalidate the memoization when
the promise throws an error.</p>
<p>This helps us with being able to re-try because since the error is not cached,
calling it again after an error retries automatically.</p>
<p>Example async function: fetch from the pokemon API</p>
<pre><code class="language-javascript">async function getPokemon() {
  const id = Math.floor(Math.random() * 150)
  const url = 'https://pokeapi.co/api/v2/pokemon/' + id
  const ret = await fetch(url)
  if (!ret.ok) {
    throw new Error(
      `Failed to fetch ${url} HTTP ${ret.status} ${ret.statusText}`,
    )
  }
  return ret.json()
}
</code></pre>
<p>Here is a technique that can be used to memoize this function</p>
<pre><code class="language-javascript">function getPokemonMemoized() {
  if (!this.promise) {
    this.promise = getPokemon().catch(e => {
      this.promise = undefined
      throw e
    })
  }
  return this.promise
}
</code></pre>
<p>The promise is held in this.promise, and the important part of this function is
that when I get an error, I clear this.promise and re-throw the error. The caller
of the function, on error, will receive the error message, but caching will not
take place, allowing retries to take place later on.</p>
<p>See <a href="https://cmdcolin.github.io/pokemon.html">https://cmdcolin.github.io/pokemon.html</a> for demo</p>
<h2>Footnote 0: Arguments to function</h2>
<p>If your function takes arguments, then you can use a hashmap associating the
argument with the promise. You may also consider using an LRU cache so that
your hashmap doesn't grow infinitely in size</p>
<p>Generally you need a way to stringify or otherwise make them able to be stored
in a Map or Object to do this.</p>
<p>See <a href="https://github.com/nodeca/promise-memoize">https://github.com/nodeca/promise-memoize</a> for example</p>
<h2>Footnote 1: Error handling of <code>fetch</code></h2>
<p>This demo also demonstrates some basic fetch error handling, and uses
<code>statusText</code> <a href="https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText">which happens to not exist in
HTTP/2</a>.
If you want a semblence of status message text in HTTP/2 you can try to use
await ret.json() (if the API returns json error messages) or await ret.text()
inside the catch clause, but note that it could cause yet another error to be
thrown</p>
<h2>Footnote 2: Global cache</h2>
<p>You could also keep a cache in a global variable, or as a property on a class,
or other methods. I have also found it useful to have a specific function for
clearing the cache, so you can get a clean slate each time a test runs in unit
testing or similar</p>
<pre><code class="language-javascript">let promise
async function getPokemonMemoized() {
  if (!promise) {
    promise = getPokemon().catch(e => {
      promise = undefined
      throw e
    })
  }
  return promise
}
function clearCache() {
  promise = undefined
}
</code></pre>
<p>You can also make a general purpose utility to memoize any promise function</p>
<pre><code class="language-javascript">function memoize(fn) {
  let promise
  return () => {
    if (!promise) {
      promise = fn().catch(e => {
        promise = undefined
        throw e
      })
    }
  }
}
</code></pre>
<h2>Footnote 3 - Aborting</h2>
<p>If you want to handle aborting, it is a bit trickier. Aborting in javascript is
handled by
<a href="https://developer.mozilla.org/en-US/docs/Web/API/AbortController/AbortController">AbortController</a>.
This is an object that gives you an
<a href="https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal">AbortSignal</a>
that can be passed to fetch calls and the like to stop a big download from
happening.</p>
<p>In our above example, if we passed an abort signal to the first call to fetch,
and then aborted it, it would abort the fetch, <a href="https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort">which throws a DOMException
called
"AbortError"</a>.
You can detect that it is an AbortError like this, and may choose not to
display or re-throw the abort exception</p>
<pre><code class="language-javascript">function isAbortException(e) {
  return e instanceof Error &#x26;&#x26; exception.name === 'AbortError'
}
</code></pre>
<p>Now, what if 5 functions call getPokemonMemoized(), all passing different abort
signals. What if the first one aborts? Then all the rest will get aborted also.
But what if we only want to abort the cached call if literally all of them
aborted? Then we may have to synthesize an abortcontroller inside our function</p>
<pre><code class="language-javascript">let promise
let abortcontroller
let listeners = 0
async function getPokemonMemoized(signal) {
  if (!promise) {
    abortcontroller = new AbortController()

    // synthesize a new signal instead of using the passed in signal
    promise = getPokemon(abortcontroller.signal).catch(e => {
      promise = undefined
      throw e
    })
  }
  if (signal) {
    listeners++
    // add listener to the passed in signal
    signal.addEventListener('abort', () => {
      listeners--
      if (listeners === 0) {
        abortcontroller.abort()
      }
    })
  }
  return promise
}
</code></pre>
<p>A library my team created,
<a href="https://github.com/GMOD/abortable-promise-cache">abortable-promise-cache</a>,
tries to help with this scenario with a cleaner abstraction.</p>
<h2>Footnote 4</h2>
<p>I have been playing through Pokemon Yellow and find it really amusing hence the
pokemon theme</p>
<p>Fun stuff: The cutting room floor wiki with unused moves, sounds, and sprites
in Pokemon Yellow <a href="https://tcrf.net/Pok%C3%A9mon_Yellow">https://tcrf.net/Pok%C3%A9mon_Yellow</a></p>
<h2>Footnote 5</h2>
<p>This blog post mentioned in a comment thread <a href="https://zansh.in/memoizer.html">https://zansh.in/memoizer.html</a> has
great interactive examples and shows the "invalidate on .catch()" behavior!</p></div><div style="margin-top:200px"></div></article></div></main></div><footer style="margin-top:100px"><a href="/">Home</a> <a href="/archive">Blog archive</a> <a href="https://github.com/cmdcolin/">Github</a> <a href="https://twitter.com/cmdcolin">Twitter</a> <a href="/projects">Projects</a> <a href="/photos">Photos</a> <a href="/rss.xml">RSS</a><a href="/about">About</a> </footer></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"post":{"title":"Memoizing async functions so that you don't cache errors","date":"2022-02-26","slug":"2022-02-26-memoize-async","html":"\u003cp\u003eThere are two hard problems in computer science: \u003ca href=\"https://martinfowler.com/bliki/TwoHardThings.html\"\u003eCache invalidation and naming\nthings\u003c/a\u003e. In this post we'll\nshow how memoize an async function, and how to invalidate the memoization when\nthe promise throws an error.\u003c/p\u003e\n\u003cp\u003eThis helps us with being able to re-try because since the error is not cached,\ncalling it again after an error retries automatically.\u003c/p\u003e\n\u003cp\u003eExample async function: fetch from the pokemon API\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"language-javascript\"\u003easync function getPokemon() {\n  const id = Math.floor(Math.random() * 150)\n  const url = 'https://pokeapi.co/api/v2/pokemon/' + id\n  const ret = await fetch(url)\n  if (!ret.ok) {\n    throw new Error(\n      `Failed to fetch ${url} HTTP ${ret.status} ${ret.statusText}`,\n    )\n  }\n  return ret.json()\n}\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003eHere is a technique that can be used to memoize this function\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"language-javascript\"\u003efunction getPokemonMemoized() {\n  if (!this.promise) {\n    this.promise = getPokemon().catch(e =\u003e {\n      this.promise = undefined\n      throw e\n    })\n  }\n  return this.promise\n}\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003eThe promise is held in this.promise, and the important part of this function is\nthat when I get an error, I clear this.promise and re-throw the error. The caller\nof the function, on error, will receive the error message, but caching will not\ntake place, allowing retries to take place later on.\u003c/p\u003e\n\u003cp\u003eSee \u003ca href=\"https://cmdcolin.github.io/pokemon.html\"\u003ehttps://cmdcolin.github.io/pokemon.html\u003c/a\u003e for demo\u003c/p\u003e\n\u003ch2\u003eFootnote 0: Arguments to function\u003c/h2\u003e\n\u003cp\u003eIf your function takes arguments, then you can use a hashmap associating the\nargument with the promise. You may also consider using an LRU cache so that\nyour hashmap doesn't grow infinitely in size\u003c/p\u003e\n\u003cp\u003eGenerally you need a way to stringify or otherwise make them able to be stored\nin a Map or Object to do this.\u003c/p\u003e\n\u003cp\u003eSee \u003ca href=\"https://github.com/nodeca/promise-memoize\"\u003ehttps://github.com/nodeca/promise-memoize\u003c/a\u003e for example\u003c/p\u003e\n\u003ch2\u003eFootnote 1: Error handling of \u003ccode\u003efetch\u003c/code\u003e\u003c/h2\u003e\n\u003cp\u003eThis demo also demonstrates some basic fetch error handling, and uses\n\u003ccode\u003estatusText\u003c/code\u003e \u003ca href=\"https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText\"\u003ewhich happens to not exist in\nHTTP/2\u003c/a\u003e.\nIf you want a semblence of status message text in HTTP/2 you can try to use\nawait ret.json() (if the API returns json error messages) or await ret.text()\ninside the catch clause, but note that it could cause yet another error to be\nthrown\u003c/p\u003e\n\u003ch2\u003eFootnote 2: Global cache\u003c/h2\u003e\n\u003cp\u003eYou could also keep a cache in a global variable, or as a property on a class,\nor other methods. I have also found it useful to have a specific function for\nclearing the cache, so you can get a clean slate each time a test runs in unit\ntesting or similar\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"language-javascript\"\u003elet promise\nasync function getPokemonMemoized() {\n  if (!promise) {\n    promise = getPokemon().catch(e =\u003e {\n      promise = undefined\n      throw e\n    })\n  }\n  return promise\n}\nfunction clearCache() {\n  promise = undefined\n}\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003eYou can also make a general purpose utility to memoize any promise function\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"language-javascript\"\u003efunction memoize(fn) {\n  let promise\n  return () =\u003e {\n    if (!promise) {\n      promise = fn().catch(e =\u003e {\n        promise = undefined\n        throw e\n      })\n    }\n  }\n}\n\u003c/code\u003e\u003c/pre\u003e\n\u003ch2\u003eFootnote 3 - Aborting\u003c/h2\u003e\n\u003cp\u003eIf you want to handle aborting, it is a bit trickier. Aborting in javascript is\nhandled by\n\u003ca href=\"https://developer.mozilla.org/en-US/docs/Web/API/AbortController/AbortController\"\u003eAbortController\u003c/a\u003e.\nThis is an object that gives you an\n\u003ca href=\"https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal\"\u003eAbortSignal\u003c/a\u003e\nthat can be passed to fetch calls and the like to stop a big download from\nhappening.\u003c/p\u003e\n\u003cp\u003eIn our above example, if we passed an abort signal to the first call to fetch,\nand then aborted it, it would abort the fetch, \u003ca href=\"https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort\"\u003ewhich throws a DOMException\ncalled\n\"AbortError\"\u003c/a\u003e.\nYou can detect that it is an AbortError like this, and may choose not to\ndisplay or re-throw the abort exception\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"language-javascript\"\u003efunction isAbortException(e) {\n  return e instanceof Error \u0026#x26;\u0026#x26; exception.name === 'AbortError'\n}\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003eNow, what if 5 functions call getPokemonMemoized(), all passing different abort\nsignals. What if the first one aborts? Then all the rest will get aborted also.\nBut what if we only want to abort the cached call if literally all of them\naborted? Then we may have to synthesize an abortcontroller inside our function\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"language-javascript\"\u003elet promise\nlet abortcontroller\nlet listeners = 0\nasync function getPokemonMemoized(signal) {\n  if (!promise) {\n    abortcontroller = new AbortController()\n\n    // synthesize a new signal instead of using the passed in signal\n    promise = getPokemon(abortcontroller.signal).catch(e =\u003e {\n      promise = undefined\n      throw e\n    })\n  }\n  if (signal) {\n    listeners++\n    // add listener to the passed in signal\n    signal.addEventListener('abort', () =\u003e {\n      listeners--\n      if (listeners === 0) {\n        abortcontroller.abort()\n      }\n    })\n  }\n  return promise\n}\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003eA library my team created,\n\u003ca href=\"https://github.com/GMOD/abortable-promise-cache\"\u003eabortable-promise-cache\u003c/a\u003e,\ntries to help with this scenario with a cleaner abstraction.\u003c/p\u003e\n\u003ch2\u003eFootnote 4\u003c/h2\u003e\n\u003cp\u003eI have been playing through Pokemon Yellow and find it really amusing hence the\npokemon theme\u003c/p\u003e\n\u003cp\u003eFun stuff: The cutting room floor wiki with unused moves, sounds, and sprites\nin Pokemon Yellow \u003ca href=\"https://tcrf.net/Pok%C3%A9mon_Yellow\"\u003ehttps://tcrf.net/Pok%C3%A9mon_Yellow\u003c/a\u003e\u003c/p\u003e\n\u003ch2\u003eFootnote 5\u003c/h2\u003e\n\u003cp\u003eThis blog post mentioned in a comment thread \u003ca href=\"https://zansh.in/memoizer.html\"\u003ehttps://zansh.in/memoizer.html\u003c/a\u003e has\ngreat interactive examples and shows the \"invalidate on .catch()\" behavior!\u003c/p\u003e"}},"__N_SSG":true},"page":"/posts/[slug]","query":{"slug":"2022-02-26-memoize-async"},"buildId":"N960rXq5BRJ06uZqtuld9","isFallback":false,"gsp":true,"scriptLoader":[]}</script></body></html>