<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><title>Memoizing async functions so that you don&#x27;t cache errors</title><meta name="next-head-count" content="3"/><link rel="shortcut icon" href="favicon.ico"/><link rel="alternate" type="application/rss+xml" href="/rss.xml"/><meta name="description" content="Blogging for the future"/><script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.25.0/prism.min.js" integrity="sha512-hpZ5pDCF2bRCweL5WoA0/N1elet1KYL5mx3LP555Eg/0ZguaHawxNvEjF6O3rufAChs16HVNhEc6blF/rZoowQ==" crossorigin="anonymous" referrerPolicy="no-referrer"></script><link rel="preload" href="/_next/static/css/9d066bf523979bbf.css" as="style"/><link rel="stylesheet" href="/_next/static/css/9d066bf523979bbf.css" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script><script src="/_next/static/chunks/webpack-8b306f51a35d80a9.js" defer=""></script><script src="/_next/static/chunks/framework-c0d8f0fd2eea5ac1.js" defer=""></script><script src="/_next/static/chunks/main-4ce9603599af9a95.js" defer=""></script><script src="/_next/static/chunks/pages/_app-d9139de5c3de3b6b.js" defer=""></script><script src="/_next/static/chunks/996-3d2a4318c0ac6f1a.js" defer=""></script><script src="/_next/static/chunks/pages/posts/%5Bslug%5D-a48b13f8f13172f9.js" defer=""></script><script src="/_next/static/cKc4FguB7rSvsTd-mZVHW/_buildManifest.js" defer=""></script><script src="/_next/static/cKc4FguB7rSvsTd-mZVHW/_ssgManifest.js" defer=""></script></head><body><div id="__next"><div><main><div><div style="margin-bottom:100px"><a href="/">Misc scribbles</a></div><article><div><h1>Memoizing async functions so that you don&#x27;t cache errors</h1><h4>2022-02-26</h4></div><p>There are two hard problems in computer science: <a href="https://martinfowler.com/bliki/TwoHardThings.html">Cache invalidation and naming
things</a>. In this post we&#x27;ll
show how memoize an async function, and how to invalidate the memoization when
the promise throws an error.</p>
<p>This helps us with being able to re-try because since the error is not cached,
calling it again after an error retries automatically.</p>
<p>Example async function: fetch from the pokemon API</p>
<pre><code class="language-javascript">async function getPokemon() {
  const id = Math.floor(Math.random() * 150)
  const url = &#x27;https://pokeapi.co/api/v2/pokemon/&#x27; + id
  const ret = await fetch(url)
  if (!ret.ok) {
    throw new Error(
      `Failed to fetch ${url} HTTP ${ret.status} ${ret.statusText}`,
    )
  }
  return ret.json()
}
</code></pre>
<p>Here is a technique that can be used to memoize this function</p>
<pre><code class="language-javascript">function getPokemonMemoized() {
  if (!this.promise) {
    this.promise = getPokemon().catch(e =&gt; {
      this.promise = undefined
      throw e
    })
  }
  return this.promise
}
</code></pre>
<p>The promise is held in this.promise, and the important part of this function is
that when I get an error, I clear this.promise and re-throw the error. The caller
of the function, on error, will receive the error message, but caching will not
take place, allowing retries to take place later on.</p>
<p>See https://cmdcolin.github.io/pokemon.html for demo</p>
<h2>Footnote 0: Arguments to function</h2>
<p>If your function takes arguments, then you can use a hashmap associating the
argument with the promise. You may also consider using an LRU cache so that
your hashmap doesn&#x27;t grow infinitely in size</p>
<p>Generally you need a way to stringify or otherwise make them able to be stored
in a Map or Object to do this.</p>
<p>See https://github.com/nodeca/promise-memoize for example</p>
<h2>Footnote 1: Error handling of <code>fetch</code></h2>
<p>This demo also demonstrates some basic fetch error handling, and uses
<code>statusText</code> <a href="https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText">which happens to not exist in
HTTP/2</a>.
If you want a semblence of status message text in HTTP/2 you can try to use
await ret.json() (if the API returns json error messages) or await ret.text()
inside the catch clause, but note that it could cause yet another error to be
thrown</p>
<h2>Footnote 2: Global cache</h2>
<p>You could also keep a cache in a global variable, or as a property on a class,
or other methods. I have also found it useful to have a specific function for
clearing the cache, so you can get a clean slate each time a test runs in unit
testing or similar</p>
<pre><code class="language-javascript">let promise
async function getPokemonMemoized() {
  if (!promise) {
    promise = getPokemon().catch(e =&gt; {
      promise = undefined
      throw e
    })
  }
  return promise
}
function clearCache() {
  promise = undefined
}
</code></pre>
<p>You can also make a general purpose utility to memoize any promise function</p>
<pre><code class="language-javascript">function memoize(fn) {
  let promise
  return () =&gt; {
    if (!promise) {
      promise = fn().catch(e =&gt; {
        promise = undefined
        throw e
      })
    }
  }
}
</code></pre>
<h2>Footnote 3 - Aborting</h2>
<p>If you want to handle aborting, it is a bit trickier. Aborting in javascript is
handled by
<a href="https://developer.mozilla.org/en-US/docs/Web/API/AbortController/AbortController">AbortController</a>.
This is an object that gives you an
<a href="https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal">AbortSignal</a>
that can be passed to fetch calls and the like to stop a big download from
happening.</p>
<p>In our above example, if we passed an abort signal to the first call to fetch,
and then aborted it, it would abort the fetch, <a href="https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort">which throws a DOMException
called
&quot;AbortError&quot;</a>.
You can detect that it is an AbortError like this, and may choose not to
display or re-throw the abort exception</p>
<pre><code class="language-javascript">function isAbortException(e) {
  return e instanceof Error &amp;&amp; exception.name === &#x27;AbortError&#x27;
}
</code></pre>
<p>Now, what if 5 functions call getPokemonMemoized(), all passing different abort
signals. What if the first one aborts? Then all the rest will get aborted also.
But what if we only want to abort the cached call if literally all of them
aborted? Then we may have to synthesize an abortcontroller inside our function</p>
<pre><code class="language-javascript">let promise
let abortcontroller
let listeners = 0
async function getPokemonMemoized(signal) {
  if (!promise) {
    abortcontroller = new AbortController()

    // synthesize a new signal instead of using the passed in signal
    promise = getPokemon(abortcontroller.signal).catch(e =&gt; {
      promise = undefined
      throw e
    })
  }
  if (signal) {
    listeners++
    // add listener to the passed in signal
    signal.addEventListener(&#x27;abort&#x27;, () =&gt; {
      listeners--
      if (listeners === 0) {
        abortcontroller.abort()
      }
    })
  }
  return promise
}
</code></pre>
<p>A library my team created,
<a href="https://github.com/GMOD/abortable-promise-cache">abortable-promise-cache</a>,
tries to help with this scenario with a cleaner abstraction.</p>
<h2>Footnote 4</h2>
<p>I have been playing through Pokemon Yellow and find it really amusing hence the
pokemon theme</p>
<p>Fun stuff: The cutting room floor wiki with unused moves, sounds, and sprites
in Pokemon Yellow https://tcrf.net/Pok%C3%A9mon_Yellow</p>
<h2>Footnote 5</h2>
<p>This blog post mentioned in a comment thread https://zansh.in/memoizer.html has
great interactive examples and shows the &quot;invalidate on .catch()&quot; behavior!</p><div style="margin-top:200px"></div></article></div></main></div><footer style="margin-top:100px"><a href="/">Home</a> <a href="/archive">Blog archive</a> <a href="https://github.com/cmdcolin/">Github</a> <a href="https://twitter.com/cmdcolin">Twitter</a> <a href="/projects">Projects</a> <a href="/photos">Photos</a> <a href="/rss.xml">RSS</a><a href="/about">About</a> </footer></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"post":{"title":"Memoizing async functions so that you don't cache errors","date":"2022-02-26","slug":"2022-02-26-memoize-async","mdxSource":{"compiledSource":"/*@jsxRuntime automatic @jsxImportSource react*/\nconst {Fragment: _Fragment, jsx: _jsx, jsxs: _jsxs} = arguments[0];\nconst {useMDXComponents: _provideComponents} = arguments[0];\nfunction _createMdxContent(props) {\n  const _components = Object.assign({\n    p: \"p\",\n    a: \"a\",\n    pre: \"pre\",\n    code: \"code\",\n    h2: \"h2\"\n  }, _provideComponents(), props.components);\n  return _jsxs(_Fragment, {\n    children: [_jsxs(_components.p, {\n      children: [\"There are two hard problems in computer science: \", _jsx(_components.a, {\n        href: \"https://martinfowler.com/bliki/TwoHardThings.html\",\n        children: \"Cache invalidation and naming\\nthings\"\n      }), \". In this post we'll\\nshow how memoize an async function, and how to invalidate the memoization when\\nthe promise throws an error.\"]\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"This helps us with being able to re-try because since the error is not cached,\\ncalling it again after an error retries automatically.\"\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"Example async function: fetch from the pokemon API\"\n    }), \"\\n\", _jsx(_components.pre, {\n      children: _jsx(_components.code, {\n        className: \"language-javascript\",\n        children: \"async function getPokemon() {\\n  const id = Math.floor(Math.random() * 150)\\n  const url = 'https://pokeapi.co/api/v2/pokemon/' + id\\n  const ret = await fetch(url)\\n  if (!ret.ok) {\\n    throw new Error(\\n      `Failed to fetch ${url} HTTP ${ret.status} ${ret.statusText}`,\\n    )\\n  }\\n  return ret.json()\\n}\\n\"\n      })\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"Here is a technique that can be used to memoize this function\"\n    }), \"\\n\", _jsx(_components.pre, {\n      children: _jsx(_components.code, {\n        className: \"language-javascript\",\n        children: \"function getPokemonMemoized() {\\n  if (!this.promise) {\\n    this.promise = getPokemon().catch(e =\u003e {\\n      this.promise = undefined\\n      throw e\\n    })\\n  }\\n  return this.promise\\n}\\n\"\n      })\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"The promise is held in this.promise, and the important part of this function is\\nthat when I get an error, I clear this.promise and re-throw the error. The caller\\nof the function, on error, will receive the error message, but caching will not\\ntake place, allowing retries to take place later on.\"\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"See https://cmdcolin.github.io/pokemon.html for demo\"\n    }), \"\\n\", _jsx(_components.h2, {\n      children: \"Footnote 0: Arguments to function\"\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"If your function takes arguments, then you can use a hashmap associating the\\nargument with the promise. You may also consider using an LRU cache so that\\nyour hashmap doesn't grow infinitely in size\"\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"Generally you need a way to stringify or otherwise make them able to be stored\\nin a Map or Object to do this.\"\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"See https://github.com/nodeca/promise-memoize for example\"\n    }), \"\\n\", _jsxs(_components.h2, {\n      children: [\"Footnote 1: Error handling of \", _jsx(_components.code, {\n        children: \"fetch\"\n      })]\n    }), \"\\n\", _jsxs(_components.p, {\n      children: [\"This demo also demonstrates some basic fetch error handling, and uses\\n\", _jsx(_components.code, {\n        children: \"statusText\"\n      }), \" \", _jsx(_components.a, {\n        href: \"https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText\",\n        children: \"which happens to not exist in\\nHTTP/2\"\n      }), \".\\nIf you want a semblence of status message text in HTTP/2 you can try to use\\nawait ret.json() (if the API returns json error messages) or await ret.text()\\ninside the catch clause, but note that it could cause yet another error to be\\nthrown\"]\n    }), \"\\n\", _jsx(_components.h2, {\n      children: \"Footnote 2: Global cache\"\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"You could also keep a cache in a global variable, or as a property on a class,\\nor other methods. I have also found it useful to have a specific function for\\nclearing the cache, so you can get a clean slate each time a test runs in unit\\ntesting or similar\"\n    }), \"\\n\", _jsx(_components.pre, {\n      children: _jsx(_components.code, {\n        className: \"language-javascript\",\n        children: \"let promise\\nasync function getPokemonMemoized() {\\n  if (!promise) {\\n    promise = getPokemon().catch(e =\u003e {\\n      promise = undefined\\n      throw e\\n    })\\n  }\\n  return promise\\n}\\nfunction clearCache() {\\n  promise = undefined\\n}\\n\"\n      })\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"You can also make a general purpose utility to memoize any promise function\"\n    }), \"\\n\", _jsx(_components.pre, {\n      children: _jsx(_components.code, {\n        className: \"language-javascript\",\n        children: \"function memoize(fn) {\\n  let promise\\n  return () =\u003e {\\n    if (!promise) {\\n      promise = fn().catch(e =\u003e {\\n        promise = undefined\\n        throw e\\n      })\\n    }\\n  }\\n}\\n\"\n      })\n    }), \"\\n\", _jsx(_components.h2, {\n      children: \"Footnote 3 - Aborting\"\n    }), \"\\n\", _jsxs(_components.p, {\n      children: [\"If you want to handle aborting, it is a bit trickier. Aborting in javascript is\\nhandled by\\n\", _jsx(_components.a, {\n        href: \"https://developer.mozilla.org/en-US/docs/Web/API/AbortController/AbortController\",\n        children: \"AbortController\"\n      }), \".\\nThis is an object that gives you an\\n\", _jsx(_components.a, {\n        href: \"https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal\",\n        children: \"AbortSignal\"\n      }), \"\\nthat can be passed to fetch calls and the like to stop a big download from\\nhappening.\"]\n    }), \"\\n\", _jsxs(_components.p, {\n      children: [\"In our above example, if we passed an abort signal to the first call to fetch,\\nand then aborted it, it would abort the fetch, \", _jsx(_components.a, {\n        href: \"https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort\",\n        children: \"which throws a DOMException\\ncalled\\n\\\"AbortError\\\"\"\n      }), \".\\nYou can detect that it is an AbortError like this, and may choose not to\\ndisplay or re-throw the abort exception\"]\n    }), \"\\n\", _jsx(_components.pre, {\n      children: _jsx(_components.code, {\n        className: \"language-javascript\",\n        children: \"function isAbortException(e) {\\n  return e instanceof Error \u0026\u0026 exception.name === 'AbortError'\\n}\\n\"\n      })\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"Now, what if 5 functions call getPokemonMemoized(), all passing different abort\\nsignals. What if the first one aborts? Then all the rest will get aborted also.\\nBut what if we only want to abort the cached call if literally all of them\\naborted? Then we may have to synthesize an abortcontroller inside our function\"\n    }), \"\\n\", _jsx(_components.pre, {\n      children: _jsx(_components.code, {\n        className: \"language-javascript\",\n        children: \"let promise\\nlet abortcontroller\\nlet listeners = 0\\nasync function getPokemonMemoized(signal) {\\n  if (!promise) {\\n    abortcontroller = new AbortController()\\n\\n    // synthesize a new signal instead of using the passed in signal\\n    promise = getPokemon(abortcontroller.signal).catch(e =\u003e {\\n      promise = undefined\\n      throw e\\n    })\\n  }\\n  if (signal) {\\n    listeners++\\n    // add listener to the passed in signal\\n    signal.addEventListener('abort', () =\u003e {\\n      listeners--\\n      if (listeners === 0) {\\n        abortcontroller.abort()\\n      }\\n    })\\n  }\\n  return promise\\n}\\n\"\n      })\n    }), \"\\n\", _jsxs(_components.p, {\n      children: [\"A library my team created,\\n\", _jsx(_components.a, {\n        href: \"https://github.com/GMOD/abortable-promise-cache\",\n        children: \"abortable-promise-cache\"\n      }), \",\\ntries to help with this scenario with a cleaner abstraction.\"]\n    }), \"\\n\", _jsx(_components.h2, {\n      children: \"Footnote 4\"\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"I have been playing through Pokemon Yellow and find it really amusing hence the\\npokemon theme\"\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"Fun stuff: The cutting room floor wiki with unused moves, sounds, and sprites\\nin Pokemon Yellow https://tcrf.net/Pok%C3%A9mon_Yellow\"\n    }), \"\\n\", _jsx(_components.h2, {\n      children: \"Footnote 5\"\n    }), \"\\n\", _jsx(_components.p, {\n      children: \"This blog post mentioned in a comment thread https://zansh.in/memoizer.html has\\ngreat interactive examples and shows the \\\"invalidate on .catch()\\\" behavior!\"\n    })]\n  });\n}\nfunction MDXContent(props = {}) {\n  const {wrapper: MDXLayout} = Object.assign({}, _provideComponents(), props.components);\n  return MDXLayout ? _jsx(MDXLayout, Object.assign({}, props, {\n    children: _jsx(_createMdxContent, props)\n  })) : _createMdxContent(props);\n}\nreturn {\n  default: MDXContent\n};\n","frontmatter":{},"scope":{}}}},"__N_SSG":true},"page":"/posts/[slug]","query":{"slug":"2022-02-26-memoize-async"},"buildId":"cKc4FguB7rSvsTd-mZVHW","isFallback":false,"gsp":true,"scriptLoader":[]}</script></body></html>